version: "3.3"
services:
  web:
    image: web
    build:
      context: ./
      dockerfile: ./build/package/docker/web/Dockerfile
    links:
      - mongo
    restart: on-failure
    depends_on:
      - mongo
    environment:
      MONGO_URL: "mongodb://mongo:27017/website-analyzer"
    ports:
      - "9000:9000"
    hostname: web
  mongo:
    image: mongo
    hostname: mongo
    ports:
      - "27017:27017"
  jobs:
    image: jobs
    build:
      context: ./
      dockerfile: ./build/package/docker/jobs/Dockerfile
    links:
      - web
    restart: on-failure
    depends_on:
      - web
    environment:
      BASE_URL: "http://web:9000/sites/"
